version: '3.8'
services:
    web:
        image: nginx:latest
        container_name: nginx
        networks:
            - my_net
        ports:
            - "80:80"
        volumes:
            - ./sites/:/sites/
            - ./nginx-hosts/:/etc/nginx/conf.d/
        links:
            - ahmet
    ahmet:
        build:
            context: ./sites
            dockerfile: ../dockerfiles/socket-redis-php/Dockerfile
        image: ahmet
        container_name: ahmet
        networks:
            - my_net
        volumes:
            - ./sites/:/sites/
        links:
            - web
networks:
  my_net:
    driver: bridge