version: '3.8'
services:
    web:
        image: nginx:latest
        container_name: nginx
        networks:
            - my_net
        ports:
            - "80:80"
        volumes:
            - ./sites/:/sites/
            - ./nginx-hosts/:/etc/nginx/conf.d/
        links:
            - socket-redis-php
    socket-redis-php:
        build:
            context: ./sites
            dockerfile: ../dockerfiles/socket-redis-php/Dockerfile
        image: socket-redis-php
        container_name: socket-redis-php
        networks:
            - my_net
        volumes:
            - ./sites/:/sites/
networks:
  my_net:
    driver: bridge